fix data-gateway startup and stop order
* add new commands install and uninstall to nuvlabox-installer. Minor improvements to installer

diff --git a/nuvlabox-engine-installer/installer b/nuvlabox-engine-installer/installer
--- a/nuvlabox-engine-installer/installer
+++ b/nuvlabox-engine-installer/installer
@@ -25,7 +25,11 @@ usage()
   echo -e " uninstall\t\t\t\tShutdown (and optionally delete) an existing NuvlaBox Engine installation"
   echo -e ""
   echo -e "INSTALL args:"
-  echo -e " (not implemented yet)"
+  echo -e " --compose-files=<list>\t\t\t(optional) Comma-separated list of compose files to deploy. If not passed, it uses all"
+  echo -e " --environment=<list>\t\t\t(optional) Comma-separated list of ENV=VALUE keypairs"
+  echo -e " --target-version=<string>\t\t(optional) NuvlaBox Engine release to be installed. If not passed, it uses the master branch"
+  echo -e " --project=<string>\t\t\t(optional) Project name used during the first installation. Default is 'nuvlabox'"
+  echo -e " --quiet\t\t\t\t(optional) Only print final status message"
   echo -e ""
   echo -e "UDPATE args:"
   echo -e " --compose-files=<list>\t\t\tComma-separated list of compose files to deploy"
@@ -33,12 +37,13 @@ usage()
   echo -e " --new-environment=<list>\t\t(optional) Comma-separated list of new ENV=VALUE keypairs"
   echo -e " --on-update-failure=<string>\t\tAction be take in case the update fails ${on_update_failure_options}. Default: ${on_update_failure}"
   echo -e " --project=<string>\t\t\tProject name used during the first installation"
-  echo -e " --quiet\t\t\t\tOnly print final status message"
+  echo -e " --quiet\t\t\t\t(optional) Only print final status message"
   echo -e " --target-version=<string>\t\tNuvlaBox Engine version to be installed. Must match a release from ${github_releases}"
   echo -e " --working-dir=<string>\t\t\tDirectory, on the host, from where the NuvlaBox Engine was installed the first time, and where the corresponding config files can be found"
   echo -e ""
   echo -e "UNINSTALL args:"
-  echo -e " (not implemented yet)"
+  echo -e " --project=<string>\t\t\t(optional) Project name used during the first installation. Default is 'nuvlabox'"
+  echo -e " --quiet\t\t\t\t(optional) Only print final status message"
 }
 
 banner_intro()
@@ -52,6 +57,15 @@ banner_intro()
   nuvlabox-engine-printer "|_|   |_|\____| \_/ |_|\_||_|______/ \___(_/ \_)  |_______)_| |_|\_|| |_|_| |_|\____)" ${1}
   nuvlabox-engine-printer "                                                                (_____|              " ${1}
   nuvlabox-engine-printer "" ${1}
+}
+
+check_args_install()
+{
+  if [[ -z $compose_files ]]
+  then
+    export compose_files=$(echo $(ls docker-compose.*) | tr ' ' ',')
+    nuvlabox-engine-printer "Installing NuvlaBox Engine with all compose files: ${compose_files}" ${quiet} "INFO" "no"
+  fi
 }
 
 check_args_update()
@@ -87,6 +101,9 @@ case ${command} in
     exit
     ;;
   update)
+    #------------------------------------------------------------------------#
+    # UPDATE
+    #------------------------------------------------------------------------#
     shift
     while [ "$1" != "" ]; do
       PARAM=`echo -e $1 | awk -F= '{print $1}'`
@@ -182,12 +199,93 @@ case ${command} in
     fi
     ;;
   uninstall)
-    echo -e "NOT IMPLEMENTED"
-    exit 0
+    #------------------------------------------------------------------------#
+    # UNINSTALL
+    #------------------------------------------------------------------------#
+    shift
+    while [ "$1" != "" ]; do
+      PARAM=`echo -e $1 | awk -F= '{print $1}'`
+      VALUE=`echo -e $1 | cut -d "=" -f 2-`
+      case $PARAM in
+        -h | --help)
+          usage
+          exit
+          ;;
+        --project)
+          export project=${VALUE}
+          ;;
+        *)
+          echo -e "${command} ERROR: unknown option $PARAM"
+          usage
+          exit 1
+          ;;
+      esac
+      shift
+    done
+    banner_intro ${quiet}
+    output=$(nuvlabox-engine-uninstall 2>&1 | tee /dev/fd/2)
+
+    if [[ $? -ne 0 ]]
+    then
+      # uninstall failed
+      nuvlabox-engine-printer "NuvlaBox Engine uninstall failed" ${quiet} "ERROR" "no"
+      exit 1
+    else
+      # uninstall successful
+      # print final message and finish
+      exit 0
+    fi
     ;;
   install)
-    echo -e "NOT IMPLEMENTED"
-    exit 0
+    #------------------------------------------------------------------------#
+    # INSTALL
+    #------------------------------------------------------------------------#
+    shift
+    while [ "$1" != "" ]; do
+      PARAM=`echo -e $1 | awk -F= '{print $1}'`
+      VALUE=`echo -e $1 | cut -d "=" -f 2-`
+      case $PARAM in
+        -h | --help)
+          usage
+          exit
+          ;;
+        --compose-files)
+          export compose_files=${VALUE}
+          ;;
+        --environment)
+          export environment=${VALUE}
+          ;;
+        --quiet)
+          export quiet=1
+          ;;
+        --project)
+          export project=${VALUE}
+          ;;
+        --target-version)
+          export target_version=${VALUE}
+          ;;
+        *)
+          echo -e "${command} ERROR: unknown option $PARAM"
+          usage
+          exit 1
+          ;;
+      esac
+      shift
+    done
+    banner_intro ${quiet}
+    check_args_install
+    output=$(nuvlabox-engine-install 2>&1 | tee /dev/fd/2)
+
+    if [[ $? -ne 0 ]]
+    then
+      # install failed
+      nuvlabox-engine-printer "NuvlaBox Engine install failed" ${quiet} "ERROR" "no"
+      exit 1
+    else
+      # install successful
+      # print final message and finish
+      exit 0
+    fi
     ;;
   *)
     echo -e "ERROR: unknown command ${command}"
