run multi command

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -56,10 +56,22 @@ jobs:
           WAIT_AVAIL_MIN: 5
           EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
           EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
-        run: $TRAVIS_BUILD_DIR/test/swarm-deploy.sh deploy $SWARM_SIZE && ip=`cat $HOME/nuvla-test-host` && $TRAVIS_BUILD_DIR/test/wait-avail.sh https://$ip/api/cloud-entry-point $WAIT_AVAIL_MIN || { >&2 echo "failed to provision Nuvla."; $TRAVIS_BUILD_DIR/test/swarm-deploy.sh terminate; exit 1; }
+        run: |
+          $TRAVIS_BUILD_DIR/test/swarm-deploy.sh deploy $SWARM_SIZE
+          ip=`cat $HOME/nuvla-test-host`
+          $TRAVIS_BUILD_DIR/test/wait-avail.sh https://$ip/api/cloud-entry-point $WAIT_AVAIL_MIN || { >&2 echo "failed to provision Nuvla."; $TRAVIS_BUILD_DIR/test/swarm-deploy.sh terminate; exit 1; }
 
       - name: Run Nuvla functional tests
-        run: cd functional-tests && export EXAMPLES_ROOT=${HOME} && export NUVLA_INSECURE=TRUE && export NUVLA_HOST=`cat $HOME/nuvla-test-host` && export SSH_PUBLIC_KEY=$HOME/.ssh/id_rsa.pub && export mname=`cat $HOME/docker-machine-master` && eval $($HOME/docker-machine env $mname) && printenv && lein do clean, test
+        run: |
+          cd functional-tests
+          export EXAMPLES_ROOT=${HOME}
+          export NUVLA_INSECURE=TRUE
+          export NUVLA_HOST=$(cat $HOME/nuvla-test-host)
+          export SSH_PUBLIC_KEY=$HOME/.ssh/id_rsa.pub
+          export mname=$(cat $HOME/docker-machine-master)
+          eval $($HOME/docker-machine env $mname)
+          printenv
+          lein do clean, test
 
       - name: Terminate Docker swarm testing cluster
         if: ${{ always() }}
